export const products = [
    {
        id: "1",
        model: "SUR589",
        price: 9.99,
        isNew: true,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Coutura",
        isLiked: false,
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 3,
            count: 6,
        },
        description:
            "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: [
            "Sophisticated and versatile dress-sport style",
            "72 diamonds adorn the elegant bezel",
            "Cabochon crown",
            "Date calendar",
            "LumiBrite hands and markers",
            "Tri-fold push-button release clasp",
        ],
        technicalData: {
            dimensions: {
                diameter: "10.5 cm",
                length: "20.5 cm",
                thickness: "1.5 cm",
            },
            movement: "Caliber 6N42",
            case: "Stainless Steel",
            strap: "Silver",
            warranty: "1 year",
            dialColor: "Blue",
            waterResistance: "100M",
            logWidth: "5.5 cm",
            crystal: "Sapphire crystal",
        },
    },
    {
        id: "2",
        model: "PRD002",
        isLiked: false,
        price: 19.99,
        isNew: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        collection: "Urban Classics",
        reviews: {
            rating: 4,
            count: 12,
        },
        description:
            "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Sleek design", "Water-resistant up to 50M", "Scratch-resistant"],
        technicalData: {
            dimensions: {
                diameter: "11 cm",
                length: "21 cm",
                thickness: "1.6 cm",
            },
            movement: "Quartz",
            case: "Brushed Steel",
            strap: "Leather",
            warranty: "1 year",
            dialColor: "Black",
            waterResistance: "50M",
            logWidth: "5 cm",
            crystal: "Mineral crystal",
        },
    },
    {
        id: "3",
        model: "PRD003",
        isLiked: false,
        price: 29.99,
        isNew: true,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        collection: "Vintage Elegance",
        reviews: {
            rating: 4.5,
            count: 8,
        },
        description: "  Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in..",
        features: ["Classic bezel", "Roman numerals", "Elegant leather strap"],
        technicalData: {
            dimensions: {
                diameter: "10 cm",
                length: "20 cm",
                thickness: "1.4 cm",
            },
            movement: "Automatic",
            case: "Rose Gold",
            strap: "Brown Leather",
            warranty: "1 year",
            dialColor: "White",
            waterResistance: "30M",
            logWidth: "4.5 cm",
            crystal: "Hardlex crystal",
        },
    },
    {
        id: "4",
        model: "PRD004",
        isLiked: false,
        price: 39.99,
        isNew: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        collection: "Bold Performance",
        reviews: {
            rating: 3.5,
            count: 10,
        },
        description: "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Chronograph", "Bold numbers", "Stainless steel strap"],
        technicalData: {
            dimensions: {
                diameter: "12 cm",
                length: "22 cm",
                thickness: "1.7 cm",
            },
            movement: "Quartz",
            case: "Titanium",
            strap: "Metal",
            warranty: "2 years",
            dialColor: "Red",
            waterResistance: "70M",
            logWidth: "5.2 cm",
            crystal: "Sapphire crystal",
        },
    },
    {
        id: "5",
        model: "PRD005",
        isLiked: false,
        price: 49.99,
        isNew: true,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        collection: "Luxury Line",
        reviews: {
            rating: 5,
            count: 5,
        },
        description: "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Diamond accents", "Sapphire crystal", "Butterfly clasp"],
        technicalData: {
            dimensions: {
                diameter: "10.8 cm",
                length: "20.8 cm",
                thickness: "1.8 cm",
            },
            movement: "Automatic",
            case: "Gold-plated",
            strap: "Leather",
            warranty: "1 year",
            dialColor: "Green",
            waterResistance: "100M",
            logWidth: "5.6 cm",
            crystal: "Mineral crystal",
        },
    }, {
        id: "11",
        model: "PRD011",
        price: 109.99,
        isNew: true,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 11",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.6,
            count: 15,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "12",
                length: "22",
                thickness: "1.8",
            },
            movement: "Movement 11",
            case: "Case 11",
            strap: "Strap 11",
            warranty: "1 year",
            dialColor: "navy",
            waterResistance: "130M",
            logWidth: "5.8",
            crystal: "Sapphire crystal",
        },
    },
    {
        id: "12",
        model: "PRD012",
        price: 119.99,
        isNew: false,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 12",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 3.9,
            count: 9,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "11.8",
                length: "21.8",
                thickness: "1.9",
            },
            movement: "Movement 12",
            case: "Case 12",
            strap: "Strap 12",
            warranty: "2 years",
            dialColor: "pink",
            waterResistance: "140M",
            logWidth: "5.9",
            crystal: "Mineral crystal",
        },
    },
    {
        id: "13",
        model: "PRD013",
        price: 129.99,
        isNew: true,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 13",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.3,
            count: 10,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "13.1",
                length: "23.1",
                thickness: "2.2",
            },
            movement: "Movement 13",
            case: "Case 13",
            strap: "Strap 13",
            warranty: "1 year",
            dialColor: "teal",
            waterResistance: "150M",
            logWidth: "6.1",
            crystal: "Sapphire crystal",
        },
    },
    {
        id: "14",
        model: "PRD014",
        price: 139.99,
        isNew: false,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 14",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.1,
            count: 8,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "12.4",
                length: "22.4",
                thickness: "1.7",
            },
            movement: "Movement 14",
            case: "Case 14",
            strap: "Strap 14",
            warranty: "2 years",
            dialColor: "gray",
            waterResistance: "160M",
            logWidth: "6.3",
            crystal: "Mineral crystal",
        },
    },
    {
        id: "15",
        model: "PRD015",
        price: 149.99,
        isNew: true,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 15",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.5,
            count: 11,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "12.9",
                length: "22.9",
                thickness: "1.6",
            },
            movement: "Movement 15",
            case: "Case 15",
            strap: "Strap 15",
            warranty: "1 year",
            dialColor: "black",
            waterResistance: "170M",
            logWidth: "6.5",
            crystal: "Hardlex crystal",
        },
    },
    {
        id: "16",
        model: "PRD016",
        price: 159.99,
        isNew: false,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 16",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.0,
            count: 13,
        },
        description: "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "13.3",
                length: "23.3",
                thickness: "2.3",
            },
            movement: "Movement 16",
            case: "Case 16",
            strap: "Strap 16",
            warranty: "2 years",
            dialColor: "silver",
            waterResistance: "180M",
            logWidth: "6.7",
            crystal: "Mineral crystal",
        },
    },
    {
        id: "17",
        model: "PRD017",
        price: 169.99,
        isNew: true,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 17",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.7,
            count: 12,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "13.7",
                length: "23.7",
                thickness: "2.0",
            },
            movement: "Movement 17",
            case: "Case 17",
            strap: "Strap 17",
            warranty: "1 year",
            dialColor: "green",
            waterResistance: "190M",
            logWidth: "6.9",
            crystal: "Hardlex crystal",
        },
    },
    {
        id: "18",
        model: "PRD018",
        price: 179.99,
        isNew: false,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 18",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.8,
            count: 16,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "13.5",
                length: "23.5",
                thickness: "2.4",
            },
            movement: "Movement 18",
            case: "Case 18",
            strap: "Strap 18",
            warranty: "2 years",
            dialColor: "red",
            waterResistance: "200M",
            logWidth: "7.1",
            crystal: "Sapphire crystal",
        },
    },
    {
        id: "19",
        model: "PRD019",
        price: 189.99,
        isNew: true,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 19",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.2,
            count: 14,
        },
        description: "Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "14.0",
                length: "24.0",
                thickness: "2.1",
            },
            movement: "Movement 19",
            case: "Case 19",
            strap: "Strap 19",
            warranty: "1 year",
            dialColor: "blue",
            waterResistance: "210M",
            logWidth: "7.3",
            crystal: "Mineral crystal",
        },
    },
    {
        id: "20",
        model: "PRD020",
        price: 199.99,
        isNew: false,
        isLiked: false,
        isCartAdded: {
            added: false,
            quantity: 1,
        },
        collection: "Collection 20",
        image: [
            "https://res.cloudinary.com/djby1yfko/image/upload/v1725875529/SUR589_1_400x600_icqcel.png",
            "https://images.pexels.com/photos/47856/rolex-wrist-watch-clock-gmt-47856.jpeg",
            "https://images.pexels.com/photos/14778525/pexels-photo-14778525.jpeg",
            "https://images.pexels.com/photos/12381409/pexels-photo-12381409.jpeg",
        ],
        reviews: {
            rating: 4.9,
            count: 17,
        },
        description: " Grim morrow then fluttered doubting and forgotten, above still door she for decorum nights longer, lenore of of ancient let sculptured this fowl lord hope. The this swung soul that perfumed see this. This fancy and in when, or before answer seraphim the into. Whom usby the and grew is bird lamplight. Truly gaunt at bird from velvet, nothing my beating upon lenore in in but at nothing. Than will nevermore what yore the opened violet tis bust, and you out this is, door gave lenore lamplight demons leave. Raven within countenance i whom name so shadows its. Upon shaven and yet an, and dying little name burned of lenore cushioned. Thereis darkness oh whispered and me when. More i though i all or sitting in. December doubtless divining token wretch and a is but. Bore nothing more is wheeled beating kind bends blessed press. Vainly respiterespite there perched upon, pallas is wondering croaking this saintly, perched let within stillness censer by than, god seraphim songs ancient it silken. Dreams pallid and heart entrance my into more curtain. Never is fancy of december a upon the, nevernevermore door the ungainly wind fancy or. Madam if rapping and the felt in.",
        features: ["Feature 1", "Feature 2", "Feature 3"],
        technicalData: {
            dimensions: {
                diameter: "14.2",
                length: "24.2",
                thickness: "2.2",
            },
            movement: "Movement 20",
            case: "Case 20",
            strap: "Strap 20",
            warranty: "2 years",
            dialColor: "purple",
            waterResistance: "220M",
            logWidth: "7.5",
            crystal: "Sapphire crystal",
        },
    },
    // Add additional products as needed with updated details.
];


export const profile = {
    name: "John Doe",
    email: "johndoe@example.com",
    image: "https://images.pexels.com/photos/1036622/pexels-photo-1036622.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    phone: "+1234567890",
    address: {
        street: "123 Main St",
        city: "Anytown",
        state: "California",
        zip: "12345"
    }
};


export const orders = [
    {
        id: "1",
        date: "2022-01-01",
        status: "Pending",
        product: products[0],
        total: 100.00,
        paymentMethod: "Credit Card",
        shippingAddress: {
            name: "John Doe",
            address: "123 Main St",
            city: "Anytown",
            state: "CA",
            zip: "12345",
        },
    },
    {
        id: "2",
        date: "2022-01-02",
        status: "Shipped",
        product: products[1],
        total: 200.00,
        paymentMethod: "PayPal",
        shippingAddress: {
            name: "Jane Smith",
            address: "456 Oak St",
            city: "Anytown",
            state: "NY",
            zip: "67890",
        },

    },
    {
        id: "3",
        date: "2022-01-03",
        status: "Delivered",
        product: products[2],
        total: 300.00,
        paymentMethod: "Credit Card",
        shippingAddress: {
            name: "Bob Johnson",
            address: "789 Elm St",
            city: "Anytown",
            state: "CA",
            zip: "12345",
        },
    },
];